apiVersion: apps/v1
kind: Deployment
metadata:
  name: tiktalk-cluster
  labels:
    app: tiktalk-cluster
spec:
  replicas: 3
  selector:
    matchLabels:
      app: tiktalk-cluster
  template:
    metadata:
      labels:
        app: tiktalk-cluster
    spec:
      containers:
      - name: tiktalk-cluster
        image: elishirk/tiktalk-backend:v7.0 
        env:
        - name: PORT
          value: "5000"
        ports:
        - containerPort: 5000
          name: "backend-server"
        resources:
          requests:
            memory: "256Mi"
            cpu: "0.1"
          limits:
            memory: "512Mi"
            cpu: "0.5"
        livenessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 60
          periodSeconds: 60
---

apiVersion: v1
kind: Service
metadata: 
  name: hip-local-api-svc
spec: 
  ports: 
     -  port: 80
        protocol: TCP
        targetPort: 5000
  selector: 
    app: tiktalk-cluster
  type: LoadBalancer
